version: "3.9"

services:
  backend:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile.backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django_project:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
